name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v3
        
      - name: setup-go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v3
        with:
          go-version: '1.17'
       
      - name: Run tests for verifier
        run: |
          set -euo pipefail
          
          go mod vendor
          # Build
          go build -mod=vendor
          # Tests
          go test -mod=vendor -v ./...
