name: Pre submits e2e
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          path: __THIS_REPO__

      - name: setup-go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: "__THIS_REPO__/go.mod"

      - name: Build verifier at HEAD
        working-directory: __THIS_REPO__
        run: |
          set -euo pipefail
          go build -o slsa-verifier ./cli/slsa-verifier

      - name: Checkout e2e verification script
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          path: __EXAMPLE_PACKAGE__
          repository: slsa-framework/example-package

      - name: Run verification script with testdata and slsa-verifier HEAD
        env:
          SLSA_VERIFIER_TESTING: "true"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Necessary to use the gh CLI.
        run: ./__THIS_REPO__/.github/workflows/scripts/e2e-cli.sh
